all:
  hosts:
    18.210.6.117:
      ansible_user: ec2-user         
      ansible_ssh_private_key_file: ./ssh_private_key.pem
    52.207.207.92:
      ansible_user: ec2-user         
      ansible_ssh_private_key_file: ./ssh_private_key.pem

  children:
    web_servers:
      hosts:
        18.210.6.117:
        52.207.207.92:
      vars:
        ansible_ssh_private_key_file: ./ssh_private_key.pem
        ansible_user: ec2-user 