plugin: amazon.aws.aws_ec2
regions:
  - us-east-1 
filters:
  "tag:Role": "WebServer" 
hostnames:
  - "tag:Name"  
keyed_groups:
  - key: "tag:Role"
    prefix: "role_"
  - key: "tag:Name"
    prefix: "name_"
