plugin: amazon.aws.aws_ec2
aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
regions:
  - us-east-1
filters:
  "tag:Role": "WebServer"
hostnames:
  - "tag:Name"
keyed_groups:
  - key: "tag:Role"
    prefix: "role_"
  - key: "tag:Name"
    prefix: "name_"

ansible_connection: ssm 
