plugin: amazon.aws.aws_ec2
aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
regions:
  - us-east-1
filters:
  tag:Role: WebServer
keyed_groups:
  - key: tags.Role
    prefix: web_
hostnames:
  - dns-name
