all:
  hosts:
    ec2-52-207-207-92.compute-1.amazonaws.com:
      ansible_ssh_private_key_file: ./ssh_private_key.pem
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3
    ec2-18-210-6-117.compute-1.amazonaws.com:
      ansible_ssh_private_key_file: ./ssh_private_key.pem
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3