---
- name: Set up Spring Boot application on AWS Linux with auto-start
  hosts: web_springboot
  become: true
  vars:
    jar_file_path: "{{ lookup('env', 'JAR_PATH') }}"
    db_pass: "{{ lookup('env', 'DB_PASS') }}"
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_url: "{{ lookup('env', 'DB_URL') }}"

  tasks:
    - name: Update system
      yum:
        name: "*"
        state: latest

    - name: Install Amazon Corretto 17
      yum:
        name: java-17-amazon-corretto-headless
        state: present

    - name: Check Java version
      command: java -version
      register: java_version
      changed_when: false

    - debug:
        msg: "Installed Java version: {{ java_version.stdout }}"

    - name: Create directory for the application
      file:
        path: "/opt/myapp"
        state: directory
        mode: '0755'

    - name: Copy .jar file from host to server
      copy:
        src: "{{ jar_file_path }}"
        dest: "/opt/myapp/app.jar"
        mode: '0644'

    - name: Create systemd unit file for auto-start
      copy:
        dest: "/etc/systemd/system/springboot-app.service"
        content: |
          [Unit]
          Description=Spring Boot Application
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/opt/myapp
          ExecStart=/usr/bin/java -jar /opt/myapp/app.jar
          Environment="POSTGRES_PASS={{ db_pass }}"
          Environment="POSTGRES_USER={{ db_user }}"
          Environment="POSTGRES_URL={{ db_url }}"
          Environment="DATABASE_TYPE=postgres"
          SuccessExitStatus=143
          Restart=always
          RestartSec=10
          StandardOutput=syslog
          StandardError=syslog
          SyslogIdentifier=springboot-app

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to apply new services
      command: systemctl daemon-reload

    - name: Enable and start Spring Boot service
      systemd:
        name: springboot-app
        enabled: yes
        state: started

    - name: Check the status of Spring Boot service
      systemd:
        name: springboot-app
        state: started
      register: spring_boot_status

    - debug:
        msg: "Spring Boot service status: {{ spring_boot_status.status }}"
