- name: Set up Petclinic Spring Boot application on AWS Linux with auto-start
  hosts: all
  become: true
  vars:
    jar_file_path: "{{ lookup('env', 'JAR_PATH') }}"
    db_pass: "{{ lookup('env', 'DB_PASS') }}"
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_url: "{{ lookup('env', 'DB_URL') }}"

  tasks:
    - name: Install Amazon Corretto 17
      ansible.builtin.dnf:
        name: java-17-amazon-corretto-headless
        state: present

    - name: Check Java version
      ansible.builtin.command:
        cmd: java -version
      register: java_version
      changed_when: false

    - name: Create directory for Petclinic application
      ansible.builtin.file:
        path: "/opt/petclinic"
        state: directory
        mode: '0755'

    - name: Copy .jar file from host to server
      ansible.builtin.copy:
        src: "{{ jar_file_path }}"
        dest: "/opt/petclinic/petclinic.jar"
        mode: '0644'

    - name: Create environment file for systemd
      ansible.builtin.copy:
        dest: "/etc/default/petclinic"
        content: |
          POSTGRES_PASS={{ db_pass }}
          POSTGRES_USER={{ db_user }}
          POSTGRES_URL={{ db_url }}
          DATABASE_TYPE=postgres
        mode: '0600'

    - name: Create systemd unit file for auto-start
      ansible.builtin.copy:
        dest: "/etc/systemd/system/petclinic.service"
        content: |
          [Unit]
          Description=Petclinic Spring Boot Application
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/opt/petclinic
          ExecStart=/usr/bin/java -jar /opt/petclinic/petclinic.jar
          EnvironmentFile=/etc/default/petclinic
          SuccessExitStatus=143
          Restart=always
          RestartSec=10
          StandardOutput=syslog
          StandardError=syslog
          SyslogIdentifier=petclinic

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd to apply new services
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start Petclinic service
      ansible.builtin.systemd:
        name: petclinic
        enabled: true
        state: started

    - name: Check the status of Petclinic service
      ansible.builtin.systemd:
        name: petclinic
        state: started
      register: petclinic_status

    - name: Display Petclinic service status
      ansible.builtin.debug:
        msg: "Petclinic service status: {{ petclinic_status.status }}"

# Ensure there's an extra newline at the end of the file
