name: Ansible deploy

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Name of the artifact to download'
        required: true

jobs:
  fetch-artifact-and-secrets:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Retrieve secrets from AWS Secrets Manager
        id: secrets
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id SPRING_PETCLINIC_DB --query SecretString --output text)
          echo "SECRET=$SECRET" >> $GITHUB_ENV
          echo $SECRET

      - name: Download Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ github.event.inputs.artifact_name }}  
          path: /opt

      - name: Check artifact
        run: |
          ls -a /opt



