name: Java Build and Test

on:
  push:
    branches:
      - '**'
    paths:
      - 'application/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'application/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Tests and Build
        working-directory: application
        run: |
          mvn test
          mvn clean package -DskipTests

      - name: Get commit hash and date
        id: commit_info
        working-directory: application
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date '+%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV

      - name: Rename JAR with commit hash and date
        working-directory: application
        run: |
          mv target/*.jar target/application-${{ env.BUILD_DATE }}-${{ env.COMMIT_HASH }}.jar

      - name: Save artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: java-artifact
          path: application/target/*.jar
