name: App CI

on:
  push:
    branches:
      - '**'
    paths:
      - 'application/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'application/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven dependencies
        working-directory: application
        run: mvn install -DskipTests  

      - name: Run Tests
        working-directory: application
        run: mvn test

      - name: Build with Maven (compile and package JAR)
        working-directory: application
        run: mvn clean package -DskipTests

      - name: Get commit hash and date
        id: commit_info
        working-directory: application
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date '+%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: release
        uses: gh-action-release/create-release@v1
        with:
          tag_name: ${{ env.COMMIT_HASH }}
          release_name: "Release ${{ env.COMMIT_HASH }} - ${{ env.BUILD_DATE }}"
          body: "Release for commit ${{ env.COMMIT_HASH }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact to GitHub Release
        uses: gh-action-release/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: application/target/*.jar
          asset_name: application-${{ env.BUILD_DATE }}-${{ env.COMMIT_HASH }}.jar
          asset_content_type: application/java-archive
          token: ${{ secrets.GITHUB_TOKEN }}
