name: Terraform CI/CD

on:
  push:
    branches:
      - '*'  
    paths:
      - 'terraform/**' 
  pull_request:
    branches:
      - main  
    paths:
      - 'terraform/**' 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: 'us-east-1'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0' 

      - name: Terraform Init
        working-directory: terraform  
        run: |
          terraform init -reconfigure

      - name: Terraform Plan
        working-directory: terraform  
        run: |
          terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' 
        working-directory: terraform  
        run: |
          terraform apply -auto-approve tfplan
